### ISSUE TITLE
Edit author information button is incorrectly being displayed for non-logged in users

### ISSUE THREAD

**Issue by eplebel** [ScienceCommons/curate_science#18]
Edit author information button is incorrectly being displayed for non-logged in users (clicking Edit opens the Edit Author modal, though at least one can't save any changes made). 

(And actually, the Edit author information button should also not be displayed for logged-in users who don't own that author page, but i have no way of testing this currently.)

e.g. https://curatescience-staging.appspot.com/app/author/etienne-lebel

**Comment by onejgordon** [comment]
Should be fixed.

**Comment by eplebel** [comment]
fixed for admin user.

i can't test whether this is also fixed for logged-in users who don't own that author page, but i'll assume it's working and close this for now.

actually @onejgordon , what non-admin user are you using for testing purposes?

**Comment by onejgordon** [comment]
I test things like user perms on the development server where it's easy to create new users of any type. I believe the same is doable on the [staging server](http://curatescience-staging.appspot.com/admin/auth/user/), but it's still missing CSS as Alex noted so it's harder to use.
